version: '2'
services:
  db:
    image: mysql:5.7
    volumes:
    - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
  wordpress:
     image: wordpress:latest
     container_name: wordpress
     restart: always
     depends_on:
       - db
     ports:
         - '8081:80'
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_NAME: wordpress
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
     volumes:
       - ./public_html:/var/www/html
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    restart: always
    ports:
    - 8082:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
networks:
 wpsite:
volumes:
  db_data: